### PR TITLE
Initial Azure pipeline

### PR DESCRIPTION
**Pull request by supunkamburugamuve**
@tjsego It seems we need to request a free tier account from Microsoft. I only get to know this when trying to run the pipeline.

I've created an initial pipeline. Need to get the authorization to test this.

https://www.compilemode.com/2021/04/no-hosted-parallelism-has-been-purchased-or-granted-azure-devops.html

### CODE REVIEW

**Comment by CompuCell3D** [comment]
@supunkamburugamuve Thank you for the draft. If you have energy to finish it perhaps I could direct you to a different repository that would be more appropriate for this type of things:
https://github.com/CompuCell3D/cc3d_build_scripts

If you could make azure directory at the top level of this repository and place your files along with instructions this would be great (PR). this is the repository where we store various cc3d-related recipes so it would be perfect for azure configuration files

**Comment by supunkamburugamuve** [comment]
@tjsego thanks. Let me try that. I think the Azure/Travis/Github actions build scripts need to be in the same repository because the builds need to be triggered by an event that happens to the repository. For example a pull request. Also, the build reports are incorporated into the repo.

But I'm not 100% sure. Let me research this a little.

**Comment by supunkamburugamuve** [comment]
@tjsego I also requested an Azure Pipeline account for this repo. But Azure didn't give me that authorization yet. Because I'm an outside contributor I'm not sure whether they will give it to me.

**Comment by CompuCell3D** [comment]
Would it help if we applied for the authorization to use Azure? We can certainly do it.

**Comment by supunkamburugamuve** [comment]
Here is the organization I've created.

https://dev.azure.com/CompuCell3D

Added both TJ and James (IU user names) to the organization. I'm trying to make you the owners of the organization. 

Here is the form we need to submit.

https://aka.ms/azpipelines-parallelism-request

**Comment by supunkamburugamuve** [comment]
I got the authorization. Now I'm checking the pipeline.

**Comment by supunkamburugamuve** [comment]
@CompuCell3D @tjsego  The build pipeline is ready. I think now the question is where should we keep the YML file. From the research I've done so far, I couldn't find a way to keep the script in a separate repository.

**Comment by CompuCell3D** [comment]
HI @supunkamburugamuve : if we are going to use azure pipeline to run integration tests I think it makes sense to keep it within current repository. A question for you : what is the main intent of this azure pipeline?

**Comment by supunkamburugamuve** [comment]
I think the immediate goals are to compile the project and run the integration tests.

**Comment by CompuCell3D** [comment]
This makes sense. Do you think the yml is ready to go? if so I can approve and merge it

**Comment by supunkamburugamuve** [comment]
@CompuCell3D the integration tests are failing at the moment. But the script is working. Do we need to do the pull request to the develop branch?

**Comment by CompuCell3D** [comment]
Hi @supunkamburugamuve  I would say `develop` would be better. Lets change the PR and we will merge it. What is failing in the regression tests?

**Comment by supunkamburugamuve** [comment]
@CompuCell3D did the pull request against the develop branch. Closing this one.

**Pull request closed without merging**
