### PR TITLE
Improvements to DiffusionSolverFE and ReactionDiffusionSolverFE

### PR DESCRIPTION
**Pull request by tjsego**
No changes to actual calculations. Just restructuring to remove redundant loops and calculations.

### CODE REVIEW

**Comment by tjsego** [comment]
I'll accomplish any other improvements in the [ECM_model](https://github.com/CompuCell3D/CompuCell3D/tree/ECM_model) branch.

**Comment by tjsego** [comment]
> Looks good. Just as a matter of curiosity, what's the speedup?

For a 500 x 500 lattice, 2 fields, no cells, 4 solver iterations per step, Dirichlet boundary conditions, 8 cores, no rendering or reaction terms, and 10k steps, I measured about a 15% speedup for DiffusionSolverFE, and about 23% for ReactionDiffusionSolverFE.

**Comment by CompuCell3D** [comment]
I think we might actually do it now an write regression testing for PDE solvers. This way we would feel much more comfortable approving changes like this one. TJ, can I ask you to write code that does comparison of PDE Solver outputs?

**Comment by tjsego** [comment]
> I think we might actually do it now an write regression testing for PDE solvers. This way we would feel much more comfortable approving changes like this one. TJ, can I ask you to write code that does comparison of PDE Solver outputs?

Definitely. We should have a test suite for future development, anyway.

**Comment by tjsego** [comment]
> There are actual changes in the output due to new code. I issued new PR that adds regresion tets for few PDE solvers and based on this comparison I saw some changes. Let's reconsile those offline

Sounds good. See [PDE_test_suite](https://github.com/CompuCell3D/CompuCell3D/tree/PDE_test_suite). I've already been putting some effort towards doing this, too.

**Pull request closed without merging**
