### PR TITLE
Feature/cell type colormap

### PR DESCRIPTION
**Pull request by CompuCell3D**
image

Added option to display color type assignments next to running simulation

### CODE REVIEW

**Review by JulianoGianlupi — APPROVED** [review]
The example figure colors-to-cell-name (not) matching is bugging me =p

**Comment by CompuCell3D** [comment]
why does it bother you? those are the type names. They are not names of the colors

**Comment by JulianoGianlupi** [comment]
> not names of the colors

suuure ;)


(in case you aren't joking: YGBR = yellow, green, blue, red)

**Comment by JulianoGianlupi** [comment]
> not names of the colors

suuure ;)


(in case you aren't joking: YGBR = yellow, green, blue, red)

**Review by JulianoGianlupi — APPROVED** [review]

**Pull request merged**
