### PR TITLE
Feature/logscaled chemotaxis

### PR DESCRIPTION
**Pull request by tjsego**
Adds formula for scaling chemotaxis parameter by center of mass concentration

### CODE REVIEW

**Comment by JulianoGianlupi** [comment]
Didn't this already exist?

line 446 -> 476

```
float ChemotaxisPlugin::log10DivisionFormula(float _flipNeighborConc, float _conc, ChemotaxisData & _chemotaxisData)
{
	return _chemotaxisData.lambda * log10(
		( 1 + _flipNeighborConc )/( 1 + _conc )
	) ;
}

float ChemotaxisPlugin::logNatDivisionFormula(float _flipNeighborConc, float _conc, ChemotaxisData & _chemotaxisData)
{
	return _chemotaxisData.lambda * log(
		( 1 + _flipNeighborConc )/( 1 + _conc )
	) ;
}

float ChemotaxisPlugin::log10DifferenceFormula(float _flipNeighborConc, float _conc, ChemotaxisData & _chemotaxisData)
{
	float diff = _flipNeighborConc - _conc;


	if ( diff <= 0 )//don't wan't NANs or infs going around
	{
		return -9E99 * _chemotaxisData.lambda;
	}

	return _chemotaxisData.lambda * log10( diff );
}

float ChemotaxisPlugin::logNatDifferenceFormula(float _flipNeighborConc, float _conc, ChemotaxisData & _chemotaxisData)
{
	float diff = _flipNeighborConc - _conc;

	if ( diff <= 0 )//don't wan't NANs or infs going around
	{
		return -9E99 * _chemotaxisData.lambda;
	}

	return _chemotaxisData.lambda * log( diff );
}
```

**Comment by tjsego** [comment]
> Didn't this already exist?
> 
> line 446 -> 476
> 
> ```
> float ChemotaxisPlugin::log10DivisionFormula(float _flipNeighborConc, float _conc, ChemotaxisData & _chemotaxisData)
> {
> 	return _chemotaxisData.lambda * log10(
> 		( 1 + _flipNeighborConc )/( 1 + _conc )
> 	) ;
> }
> 
> float ChemotaxisPlugin::logNatDivisionFormula(float _flipNeighborConc, float _conc, ChemotaxisData & _chemotaxisData)
> {
> 	return _chemotaxisData.lambda * log(
> 		( 1 + _flipNeighborConc )/( 1 + _conc )
> 	) ;
> }
> 
> float ChemotaxisPlugin::log10DifferenceFormula(float _flipNeighborConc, float _conc, ChemotaxisData & _chemotaxisData)
> {
> 	float diff = _flipNeighborConc - _conc;
> 
> 
> 	if ( diff <= 0 )//don't wan't NANs or infs going around
> 	{
> 		return -9E99 * _chemotaxisData.lambda;
> 	}
> 
> 	return _chemotaxisData.lambda * log10( diff );
> }
> 
> float ChemotaxisPlugin::logNatDifferenceFormula(float _flipNeighborConc, float _conc, ChemotaxisData & _chemotaxisData)
> {
> 	float diff = _flipNeighborConc - _conc;
> 
> 	if ( diff <= 0 )//don't wan't NANs or infs going around
> 	{
> 		return -9E99 * _chemotaxisData.lambda;
> 	}
> 
> 	return _chemotaxisData.lambda * log( diff );
> }
> ```

No, this feature is for scaling by measurements at the center of mass, rather than by measurements at an interface.

**Comment by JulianoGianlupi** [comment]
Ah, got it

**Review by JulianoGianlupi — APPROVED** [review]

**Review by CompuCell3D — APPROVED** [review]
looks good

**Pull request merged**
