### PR TITLE
Convert FieldExtractor to parallel implementation

### PR DESCRIPTION
**Pull request by aFuerst**
Re-write all the functions in FieldExtractor using OpenMP parallelism
All still work serially, works with any number of parallel threads

### CODE REVIEW

**Comment by CompuCell3D** [comment]
@aFuerst Thank you for all the work you have done. It looks very good at first glance. Out of curiosity which platforms have you tested the code on? I will definitely take it for a test drive and will be in touch shortly

**Comment by aFuerst** [comment]
@CompuCell3D I have tested on Windows 10 and Linux (Ubuntu)

**Review by tjsego — APPROVED** [review]
Nice work.

**Comment by CompuCell3D** [comment]
I tried compiling it on OSX and I am getting some CMake errors (i.e. I dont even get to compilation step) Will need to investigate further to see whats going on

**Comment by CompuCell3D** [comment]
The speed up is greatest for 2D visualizations. Here is comparison of timing from cellsort with 2D on with new (serial graophics) and old code (parallel graphics) we used CPU 8 cores

New code:

            Total Steppable Time:        0.00 ( 0.0%)
    Compiled Code (C++) Run Time:        9.26 (82.0%)
                      Other Time:        2.03 (18.0%)
-----------------------------------------------------------

Old code
            Total Steppable Time:        0.00 ( 0.0%)
    Compiled Code (C++) Run Time:       10.37 (55.2%)
                      Other Time:        8.40 (44.7%)
-----------------------------------------------------------

Other time is a good proxy for time spent on visualization - we can see 4+x  speedup of 2D graphics 

3D speedups in visualizations are less impressive but since most people use 2D visualization this code improvement is really good

**Pull request merged**
