### PR TITLE
Logger functionality for CC3D

### PR DESCRIPTION
**Pull request by DeconvFFT**
This PR adds debug and trace level logs to CompuCell3D
- Logs can be enabled or disabled in the player by CompuCell.Logger.enableConsoleLogging(log level) and CompuCell.Logger.disableConsoleLogging(log level)
- Ignored muParser, Basic, ViennaCL, Eigen modules

### CODE REVIEW

**Comment by CompuCell3D** [comment]
there are compilation errors and it is likely that you have started with som obsolete branch that still contains BasicUtils. I would suggest that you branch off from current `develop` and copy all your modifications to newly created branch. I think this will be the easies path forward. Looking at the improvements that you have made it all looks good to me so lets do this one more step and we will merge the PR
`In file included from /Users/m/src/CompuCell3D/CompuCell3D/core/BasicUtils/BasicException.cpp:26:
In file included from /Users/m/src/CompuCell3D/CompuCell3D/core/BasicUtils/BasicException.h:30:
/Users/m/src/CompuCell3D/CompuCell3D/core/BasicUtils/BasicSmartPointer.h:231:13: error: 'BasicException' is an incomplete type
      throw BasicException(std::string("BasicSmartPointer: Cannot adopt a") +
            ^
/Users/m/src/CompuCell3D/CompuCell3D/core/BasicUtils/BasicSmartPointer.h:35:7: note: forward declaration of 'BasicException'
class BasicException;
      ^
/Users/m/src/CompuCell3D/CompuCell3D/core/BasicUtils/BasicSmartPointer.h:231:7: error: cannot throw object of incomplete type 'BasicException'
      throw BasicException(std::string("BasicSmartPointer: Cannot adopt a") +
      ^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/m/src/CompuCell3D/CompuCell3D/core/BasicUtils/BasicSmartPointer.h:35:7: note: forward declaration of 'BasicException'
class BasicException;
      ^
/Users/m/src/CompuCell3D/CompuCell3D/core/BasicUtils/BasicSmartPointer.h:265:2: error: 'BasicException' is an incomplete type
        BasicException("BasicSmartPointer: Can't dereference a NULL pointer!");
        ^
/Users/m/src/CompuCell3D/CompuCell3D/core/BasicUtils/BasicSmartPointer.h:35:7: note: forward declaration of 'BasicException'
class BasicException;
`

**Review by CompuCell3D — CHANGES_REQUESTED** [review]
Lets branch of off current develop branch to eliminate compilation errors. Take a look at my comment under the PR page for details

**Comment by CompuCell3D** [comment]
BTW, I was building the code on OSX on M1 with clang 14

**Comment by DeconvFFT** [comment]
@CompuCell3D I don't think we were able to generate a build for m1 mac, but I will rebase it off the develop branch, add my changes and try again. @tjsego  not sure if our Logger functionality should compile with m1 mac

**Comment by tjsego** [comment]
> Lets branch of off current develop branch to eliminate compilation errors. Take a look at my comment under the PR page for details

That's the intent for this PR. I'm handling rebasing, then @DeconvFFT will pull changes and issue the PR to develop.

**Comment by CompuCell3D** [comment]
@DeconvFFT if you start from develop branch then things will compile smoothly on M1 and others. I have not seen anything in your code that would say otherwise. In any case, thank you for taking the effort to add this long overdue feature

**Pull request merged**
